name: 'Emscripten'

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - BuildType: Release
          Backend: SDL2
          SharewareDemo: OFF
        - BuildType: Release
          Backend: SDL2
          SharewareDemo: ON

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Install Emscripten SDK'
      run: |
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        cd ..
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: 'Configure CMake'
      run: |
        export OS=emscripten
        export CC=emcc
        
        source ../emsdk/emsdk_env.sh
        
        emcmake cmake -B ./_build/ -D CMAKE_BUILD_TYPE=${{ matrix.BuildType }} -D NCINE_LINKTIME_OPTIMIZATION=ON -D NCINE_PREFERRED_BACKEND=${{ matrix.Backend }} -D SHAREWARE_DEMO_ONLY=${{ matrix.SharewareDemo }}

    - name: 'Build'
      run: |
        make -j $(nproc) -C ./_build/

    #- name: 'Create Package'
    #  run: |
    #    mkdir ./_package/
    #    cp -f ./_build/jazz2 ./_package/jazz2
    #    cp -f -r ./Content/ ./_package/Content/
    #    
    #- name: 'Upload Package'
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: Jazz²_linux_${{ matrix.CC }}_${{ matrix.Backend }}
    #    path: ./_package/
        